<?php

namespace Nicorette\CentralBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Query\ResultSetMappingBuilder;
use Doctrine\DBAL\Connection;

/**
 * Answer Repository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ChoiceRepository extends EntityRepository {

    public function findChoicesIdsForQuestion($questionId){
        $qb = $this->createQueryBuilder('c')
            ->select('c.id')
            ->where('c.question = :qId')
            ->setParameter('qId',$questionId);
        $results = $qb->getQuery()->getResult();
            return $results;
    }
}