<?php

namespace Nicorette\CentralBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Query\ResultSetMappingBuilder;
use Doctrine\DBAL\Connection;

/**
 * Answer Repository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContractRepository extends EntityRepository {
    /**
     * @param $patient
     * @return null
     */
    public function getLastContractsByUser($patient){
        $qb = $this->createQueryBuilder('c')
            ->where('c.patient = :pid')
            ->orderBy('c.id', 'DESC')
//            ->setMaxResults($limit )
            ->setParameter('pid',$patient->getId());
        $results = $qb->getQuery()->getResult();
        return isset($results[0])?$results[0]:null;
    }

    public function getContractedUsers(){
        $today=date('Y-m-d 00:00:00');
        $qb=$this->createQueryBuilder('c')
            ->where('c.stopDate <= :today')
            ->orWhere('c.lastCigarette <= :today')
            ->setParameter('today',$today);
        return $qb->getQuery()->getResult();

    }

}