<?php

namespace Nicorette\CentralBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * PatientEconomyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PatientEconomyRepository extends EntityRepository
{
	public function findEconomyByUuid($uuid){
		$qb = $this->createQueryBuilder('e')
		->join('e.patient', 'p')
		->where('p.janrainId = :uuid')
		->setParameter('uuid', $uuid);
		$result = $qb->getQuery()->getResult();
		return isset($result[0])?$result[0]:null;
	}
}
