<?php

namespace Nicorette\CentralBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Query\ResultSetMappingBuilder;
use Doctrine\DBAL\Connection;

/**
 * Answer Repository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PointHistoryRepository extends EntityRepository
{
    public function getLastPointAddedForToday($type='goal_achieved',$patient){
        $qb = $this->createQueryBuilder('ph')
            ->join('ph.patient', 'p')
            ->where('p.id = :pid')
            ->andWhere('ph.type = :type')
            ->andWhere('ph.createdAt >= :today')
            ->setParameter('pid', $patient->getId())
            ->setParameter('today',new \Datetime(date('Y-m-d')))
            ->setParameter('type', $type);
        $results = $qb->getQuery()->getResult();
        return $results&&$results[0]?$results[0]:null;
    }

    public function getPointsByPatient($patient, $startDate = NULL, $endDate = NULL){
    	$qb = $this->createQueryBuilder('ph')
				    	->join('ph.patient', 'p')
				    	->where('p.id = :pid')
				    	->setParameter('pid', $patient->getId())
    					->orderBy('ph.createdAt', 'ASC');
    	if( $startDate != NULL ){
    		$qb->andWhere('ph.createdAt >= :sd')
			   ->setParameter('sd', $startDate);
    	}
    	if( $endDate != NULL ){
    		$qb->andWhere('ph.createdAt <= :ed')
			   ->setParameter('ed', $endDate);
    	}
    	return $qb->getQuery()->getResult();
    }
}