<?php

namespace Nicorette\CentralBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Query\ResultSetMappingBuilder;
use Doctrine\DBAL\Connection;

/**
 * QuizAnswer Repository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class QuizAnswerRepository extends EntityRepository {
	
	public function findAnswersQuizByPatientAndCode($patient, $code){
		$qb = $this->createQueryBuilder('qa')
						->join('qa.patient', 'p')
						->join('qa.quiz', 'q')
						->where('p.id = :pid')
						->Andwhere('q.code = :code')
						->setParameter('pid',$patient->getId())
						->setParameter('code',$code);
		return $qb->getQuery()->getResult();
	}
	
	public function findAnswerQuizByPatientAndCode($patient, $code){
		$qb = $this->createQueryBuilder('qa')
		->join('qa.patient', 'p')
		->join('qa.quiz', 'q')
		->where('p.id = :pid')
		->Andwhere('q.code = :code')
		->setParameter('pid',$patient->getId())
		->setParameter('code',$code);
		$results = $qb->getQuery()->getResult();
		return isset($results[0])?$results[0]:null;
	}

    public function findlastAnswerQuizByPatientAndCode($patient, $code){
		$qb = $this->createQueryBuilder('qa')
		->join('qa.patient', 'p')
		->join('qa.quiz', 'q')
		->where('p.id = :pid')
		->Andwhere('q.code = :code')
		->setParameter('pid',$patient->getId())
		->setParameter('code',$code)
        ->orderBy('qa.createdAt', 'DESC');
		$results = $qb->getQuery()->getResult();
		return isset($results[0])?$results[0]:null;
	}

}