<?php

namespace Proxies\__CG__\Nicorette\CentralBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Product extends \Nicorette\CentralBundle\Entity\Product implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', 'id', 'name', 'categoryName', 'description', 'picture', 'secondPicture', 'posoSup', 'posoInf', 'choice');
        }

        return array('__isInitialized__', 'id', 'name', 'categoryName', 'description', 'picture', 'secondPicture', 'posoSup', 'posoInf', 'choice');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Product $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setDescription($description)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDescription', array($description));

        return parent::setDescription($description);
    }

    /**
     * {@inheritDoc}
     */
    public function getDescription()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDescription', array());

        return parent::getDescription();
    }

    /**
     * {@inheritDoc}
     */
    public function setName($name)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setName', array($name));

        return parent::setName($name);
    }

    /**
     * {@inheritDoc}
     */
    public function getName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getName', array());

        return parent::getName();
    }

    /**
     * {@inheritDoc}
     */
    public function setCategoryName($categoryName)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCategoryName', array($categoryName));

        return parent::setCategoryName($categoryName);
    }

    /**
     * {@inheritDoc}
     */
    public function getCategoryName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCategoryName', array());

        return parent::getCategoryName();
    }

    /**
     * {@inheritDoc}
     */
    public function setPicture($picture)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPicture', array($picture));

        return parent::setPicture($picture);
    }

    /**
     * {@inheritDoc}
     */
    public function getPicture()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPicture', array());

        return parent::getPicture();
    }

    /**
     * {@inheritDoc}
     */
    public function setSecondPicture($secondPicture)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSecondPicture', array($secondPicture));

        return parent::setSecondPicture($secondPicture);
    }

    /**
     * {@inheritDoc}
     */
    public function getSecondPicture()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSecondPicture', array());

        return parent::getSecondPicture();
    }

    /**
     * {@inheritDoc}
     */
    public function setPosoSup($posoSup)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPosoSup', array($posoSup));

        return parent::setPosoSup($posoSup);
    }

    /**
     * {@inheritDoc}
     */
    public function getPosoSup()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPosoSup', array());

        return parent::getPosoSup();
    }

    /**
     * {@inheritDoc}
     */
    public function setPosoInf($posoInf)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPosoInf', array($posoInf));

        return parent::setPosoInf($posoInf);
    }

    /**
     * {@inheritDoc}
     */
    public function getPosoInf()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPosoInf', array());

        return parent::getPosoInf();
    }

    /**
     * {@inheritDoc}
     */
    public function setChoice($choice)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setChoice', array($choice));

        return parent::setChoice($choice);
    }

    /**
     * {@inheritDoc}
     */
    public function getChoice()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getChoice', array());

        return parent::getChoice();
    }

}
