<?php

namespace Proxies\__CG__\Nicorette\CentralBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Question extends \Nicorette\CentralBundle\Entity\Question implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array('choices' => NULL);



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {
        unset($this->choices);

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }

    /**
     * 
     * @param string $name
     */
    public function __get($name)
    {
        if (array_key_exists($name, $this->__getLazyProperties())) {
            $this->__initializer__ && $this->__initializer__->__invoke($this, '__get', array($name));

            return $this->$name;
        }

        trigger_error(sprintf('Undefined property: %s::$%s', __CLASS__, $name), E_USER_NOTICE);
    }

    /**
     * 
     * @param string $name
     * @param mixed  $value
     */
    public function __set($name, $value)
    {
        if (array_key_exists($name, $this->__getLazyProperties())) {
            $this->__initializer__ && $this->__initializer__->__invoke($this, '__set', array($name, $value));

            $this->$name = $value;

            return;
        }

        $this->$name = $value;
    }

    /**
     * 
     * @param  string $name
     * @return boolean
     */
    public function __isset($name)
    {
        if (array_key_exists($name, $this->__getLazyProperties())) {
            $this->__initializer__ && $this->__initializer__->__invoke($this, '__isset', array($name));

            return isset($this->$name);
        }

        return false;
    }

    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', 'id', 'name', 'secondName', 'inputType', 'answerRequired', 'answerMultiple', 'questionOrder', 'quiz', 'choices');
        }

        return array('__isInitialized__', 'id', 'name', 'secondName', 'inputType', 'answerRequired', 'answerMultiple', 'questionOrder', 'quiz');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Question $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

            unset($this->choices);
        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function setId($id)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setId', array($id));

        return parent::setId($id);
    }

    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setName($name)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setName', array($name));

        return parent::setName($name);
    }

    /**
     * {@inheritDoc}
     */
    public function getName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getName', array());

        return parent::getName();
    }

    /**
     * {@inheritDoc}
     */
    public function setSecondName($secondName)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSecondName', array($secondName));

        return parent::setSecondName($secondName);
    }

    /**
     * {@inheritDoc}
     */
    public function getSecondName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSecondName', array());

        return parent::getSecondName();
    }

    /**
     * {@inheritDoc}
     */
    public function setInputType($inputType)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setInputType', array($inputType));

        return parent::setInputType($inputType);
    }

    /**
     * {@inheritDoc}
     */
    public function getInputType()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getInputType', array());

        return parent::getInputType();
    }

    /**
     * {@inheritDoc}
     */
    public function setAnswerRequired($answerRequired)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAnswerRequired', array($answerRequired));

        return parent::setAnswerRequired($answerRequired);
    }

    /**
     * {@inheritDoc}
     */
    public function getAnswerRequired()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAnswerRequired', array());

        return parent::getAnswerRequired();
    }

    /**
     * {@inheritDoc}
     */
    public function setAnswerMultiple($answerMultiple)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAnswerMultiple', array($answerMultiple));

        return parent::setAnswerMultiple($answerMultiple);
    }

    /**
     * {@inheritDoc}
     */
    public function getAnswerMultiple()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAnswerMultiple', array());

        return parent::getAnswerMultiple();
    }

    /**
     * {@inheritDoc}
     */
    public function setQuestionOrder($questionOrder)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setQuestionOrder', array($questionOrder));

        return parent::setQuestionOrder($questionOrder);
    }

    /**
     * {@inheritDoc}
     */
    public function getQuestionOrder()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getQuestionOrder', array());

        return parent::getQuestionOrder();
    }

    /**
     * {@inheritDoc}
     */
    public function setQuiz(\Nicorette\CentralBundle\Entity\Quiz $quiz)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setQuiz', array($quiz));

        return parent::setQuiz($quiz);
    }

    /**
     * {@inheritDoc}
     */
    public function getQuiz()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getQuiz', array());

        return parent::getQuiz();
    }

    /**
     * {@inheritDoc}
     */
    public function addChoice($choice)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addChoice', array($choice));

        return parent::addChoice($choice);
    }

    /**
     * {@inheritDoc}
     */
    public function removeChoice($choice)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeChoice', array($choice));

        return parent::removeChoice($choice);
    }

    /**
     * {@inheritDoc}
     */
    public function getChoices()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getChoices', array());

        return parent::getChoices();
    }

}
